# Generated by Django 4.1.2 on 2022-10-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='کاربر')),
                ('exchange_name', models.CharField(choices=[('okex', 'okex')], max_length=50, verbose_name='صرافی مربوطه')),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا فعال است؟')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'حساب مشتریان در صرافی ها',
                'verbose_name_plural': 'حساب مشتریان در صرافی ها',
            },
        ),
    ]
