# Generated by Django 4.1.2 on 2022-10-21 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, verbose_name='ثبت کننده سیگنال')),
                ('symbol', models.CharField(max_length=30, verbose_name='جفت ارز')),
                ('entry_point', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='نقطه ورود')),
                ('stop_loss', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='حد ضرر')),
                ('tp1', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='حد سود ۱')),
                ('tp2', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='حد سود ۲')),
                ('tp3', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='حد سود ۳')),
                ('tp4', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='حد سود ۴')),
                ('tp5', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='حد سود ۵')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'سیگنال',
                'verbose_name_plural': 'سیگنال ها',
            },
        ),
    ]
