# Generated by Django 4.1.2 on 2022-10-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0002_alter_newsignal_stop_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsignal',
            name='entry_point',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='نقطه ورود'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='tp1',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='حد سود ۱'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='tp2',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='حد سود ۲'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='tp3',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='حد سود ۳'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='tp4',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='حد سود ۴'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='tp5',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='حد سود ۵'),
        ),
    ]
