# Generated by Django 4.1.2 on 2022-10-21 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0004_newsignal_position_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsignal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت سیگنال'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='position_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('open', 'open'), ('sl_triggered', 'sl_triggered'), ('tp1_triggered', 'tp1_triggered'), ('tp2_triggered', 'tp2_triggered'), ('tp3_triggered', 'tp3_triggered'), ('tp4_triggered', 'tp4_triggered'), ('tp5_triggered', 'tp5_triggered'), ('Done', 'Done')], default='waiting', max_length=50, verbose_name='وضعیت معامله'),
        ),
        migrations.AlterField(
            model_name='newsignal',
            name='symbol',
            field=models.CharField(choices=[('ETH/USDT', 'ETH/USDT'), ('BTC/USDT', 'BTC/USDT'), ('XRP/USDT', 'XRP/USDT'), ('DYDX/USDT', 'DYDX/USDT'), ('LTC/USDT', 'LTC/USDT'), ('APT/USDT', 'APT/USDT'), ('AAVE/USDT', 'AAVE/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('COMP/USDT', 'COMP/USDT'), ('SUSHI/USDT', 'SUSHI/USDT'), ('MATIC/USDT', 'MATIC/USDT'), ('TRX/USDT', 'TRX/USDT'), ('RSR/USDT', 'RSR/USDT')], max_length=30, verbose_name='جفت ارز'),
        ),
    ]
