# Generated by Django 4.1.2 on 2022-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0005_alter_newsignal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsignal',
            name='is_market',
            field=models.BooleanField(default=False, verbose_name='آیا میخواهید مارکت انجام شود؟ '),
        ),
    ]
