# Generated by Django 4.1.2 on 2022-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0006_newsignal_is_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsignal',
            name='leverage',
            field=models.IntegerField(default=1, verbose_name='تعیین لورج (بیشتر از ۵۰ اوردر ثبت نخواهد شد)'),
        ),
    ]
