# Generated by Django 4.1.2 on 2022-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0007_newsignal_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsignal',
            name='side',
            field=models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], default='LONG', max_length=10, verbose_name='انتخاب جهت معامله'),
        ),
    ]
