# Generated by Django 4.1.2 on 2022-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0008_newsignal_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsignal',
            name='close_strategy',
            field=models.CharField(choices=[('close_all', 'همه چیز را ببند و کنسل کن'), ('nothing', 'کاری نکن')], default='nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='newsignal',
            name='volume',
            field=models.IntegerField(default=20, verbose_name='تعیین حجم معامله بر اساس دلار'),
        ),
    ]
