# Generated by Django 4.1.2 on 2022-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_center', '0009_newsignal_close_strategy_newsignal_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsignal',
            name='close_strategy',
        ),
        migrations.AddField(
            model_name='newsignal',
            name='remove_signal_strategy',
            field=models.CharField(choices=[('close_all', 'همه چیز را ببند و کنسل کن'), ('nothing', 'کاری نکن')], default='nothing', max_length=100, verbose_name='استراتژی حذف سیگنال'),
        ),
    ]
